### ISSUE TITLE
Improve exception handling for better user experiance 

### ISSUE THREAD

**Issue by Agent-Hellboy** [RstEyeApp/rsteye#15]
Handle below exception 
```bash
./RstEyeApp
^C^C
^C^X
^CException in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1967, in __call__
  File "tkinter/__init__.py", line 861, in callit
  File "app.py", line 147, in show_image
  File "tkinter/__init__.py", line 1504, in mainloop
KeyboardInterrupt
^C^C^C
^C
^CTraceback (most recent call last):
  File "app.py", line 166, in <module>
  File "app.py", line 160, in start
  File "tkinter/__init__.py", line 1504, in mainloop
KeyboardInterrupt
[669410] Failed to execute script 'app' due to unhandled exception!
```

**Comment by Agent-Hellboy** [comment]
The error was because systemd does'ty have access to graphic interface 

we need to use the service at user level 
it doesn't have access to any DISPLAY system

@coderadditai what do you think?

**Comment by Agent-Hellboy** [comment]
@coderabbitai I have added a PR #16  for this issue , please review it in this context
